name: ci-test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Check out code into the Go mudule directory
        uses: actions/checkout@v3

      - name: Install Golang-migration
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /bin/migrate
          which migrate

      - name: Run migrations
        run: make migrateup

      - name: Check postgres status
        run: |
          sudo systemctl enable postgresql
          sudo systemctl restart postgresql
          sudo systemctl status postgresql

      - name: Check postgres password
        run: |
          psql -U postgres -h localhost
          SELECT * FROM pg_shadow WHERE usename='root';

      - name: Set PostgreSQL root password
        run: |
          docker exec postgres psql -U root -c "ALTER USER root WITH PASSWORD 'postgres';"
        env:
          PGHOST: localhost
          PGUSER: root
          PGPASSWORD: postgres
          PGDATABASE: simple_bank

      - name: Test
        run: make test

      - name: Show PostgreSQL logs
        run: docker logs postgres
