name: ci-test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: simplebank
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Check out code into the Go mudule directory
        uses: actions/checkout@v3

      - name: Install Golang-migration
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /bin/migrate
          which migrate

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-clien

        # queries database with postgres client
      - name: Query database
        run: psql -h postgres -d simplebank -U root -c 'SELECT 1;'
        env:
          # postgress password is required; alternatively, you can run:
          # `PGPASSWORD=postgres_password psql ...`
          PGPASSWORD: postgres

      - name: Run migrations
        run: make migrateup

      - name: Check postgres status
        run: |
          sudo systemctl enable postgresql
          sudo systemctl restart postgresql
          sudo systemctl status postgresql

      - name: Get dependencies
        run: |
          go get github.com/stretchr/testify/require
          go get github.com/lib/pq
          go get github.com/stretchr/testify/require

      - name: Tidy
        run: go mod tidy

      - name: Test
        run: go test -v -cover -race ./...
